### ISSUE TITLE
"microgateway-coresident" link is broken in docs

### ISSUE THREAD

**Issue by bunkerdives** [apigee/cloud-foundry-apigee#10]
First bullet point here: https://github.com/apigee/cloud-foundry-apigee/docs/apigee-service-broker-prerequisites.md

The "microgateway-coresident" link leads to a 404.

**Comment by KyleWiese** [comment]
https://github.com/apigee/cloud-foundry-apigee/blob/master/docs/apigee-service-broker-prerequisites.md should have the correct link now. Thanks for pointing this out!
