### ISSUE TITLE
Microgateway Coresident plan - Give users ability to select which version of Node.js to install

### ISSUE THREAD

**Issue by swilliams11** [apigee/cloud-foundry-apigee#4]
We should surface the Node.js version via an environment variable.   So the user should have the ability to either specify where the Node.js tarball is located or instruct the decorator to download from an explicit site; either nodejs.org or some other internal site which has the node version they want.  

https://github.com/apigee/cloud-foundry-apigee/blob/master/microgateway_decorator/bin/compile

The current code is always points to Node.js 6.11.3.  
```
wget --quiet https://nodejs.org/dist/v6.11.3/node-v6.11.3-linux-x64.tar.gz
tar --touch --strip-components 1 -xzf node-v6.11.3-linux-x64.tar.gz -C $BUILD_DIR/tmp/node
rm node-v6.11.3-linux-x64.tar.gz
export PATH=$PATH:${BUILD_DIR}/tmp/node/bin
```

I've been working with another client on this issue and their PCF environment doesn't have internet access. I know we can modify the code here, but we should include this as a standard feature for the benefit of other clients.

**Comment by swilliams11** [comment]
I started implementing this here and I'm still testing it.  I'll submit a pull request once my testing is complete. 

https://github.com/swilliams11/cloud-foundry-apigee/commit/709fe69335f3fbf4e1fb54c3f772cd66049eb0e2

**Comment by KyleWiese** [comment]
Closing this as this was included in the latest release.
