### ISSUE TITLE
Microgateway Coresdent Plan - Allow user to select Edge Microgateway version

### ISSUE THREAD

**Issue by swilliams11** [apigee/cloud-foundry-apigee#5]
We should give the user the ability to select which Edge Microgateway they want to use. 

Current code
```
git clone https://github.com/apigee-internal/microgateway.git $BUILD_DIR/tmp/edgemicro
(cd $BUILD_DIR/tmp/edgemicro && git checkout tags/v2.5.8)
npm --prefix $BUILD_DIR/tmp/edgemicro install
```

Its fixed at v2.5.8, but now Edge Microgateway is 2.5.19.

**Comment by swilliams11** [comment]
See the pull request here.
https://github.com/apigee/cloud-foundry-apigee/pull/7

**Comment by KyleWiese** [comment]
Closing this as this was included in the latest release.
